### ISSUE TITLE
Predicate fails with message: Unsupported operator IN [DATALDAP-62]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-ldap#82]
**[Alex](https://jira.spring.io/secure/ViewProfile.jspa?name=lindstrong)** opened **[DATALDAP-62](https://jira.spring.io/browse/DATALDAP-62?redirect=false)** and commented

I have a POJO class that contains LDAP attributes. The class is annotated with `@Entry` annotation. The entity has some fields as a collection (i.e. Set\<String>) but most of the POJO fields are just String values.
When I try to use LdapRepository's findAll method with Predicate to search through multi-valued fields with using Collection.contains(...) method the spring-data-ldap throws the exception:

```
java.lang.UnsupportedOperationException: Unsupported operator IN
at org.springframework.data.ldap.repository.support.LdapSerializer.visit(LdapSerializer.java:108)
at org.springframework.data.ldap.repository.support.LdapSerializer.visit(LdapSerializer.java:37)
at com.querydsl.core.types.OperationImpl.accept(OperationImpl.java:83)
```

I was able to trace the problem and it looks like when Collection type of an attribute is used for a Predicate's query then QueryDSL provides IN operation which is not supported by Spring's LdapSerializer class.
Here is the sample of the Predicate:

```
QPerson person = QPerson.person;
return person.studentAliases.contains(alias).or(person.employeeAliases.contains(alias));
```

Is it possible to add support for IN operation same way as EQ operator so DATA-LDAP module processes multi-valued attributes without any issues?

---
No further details from [DATALDAP-62](https://jira.spring.io/browse/DATALDAP-62?redirect=false)

**Comment by nemogpt** [comment]
Could someone assign this to me if it's still a priority to resolve?

**Comment by Ashish-CodeJourney** [comment]
Since the previous claim appears inactive, I'd like to pick this up.

I verified the issue still reproduces on current `main`: `Ops.IN` is not handled in `LdapSerializer`, so a predicate like `person.attributes.contains(value)` on a multi-valued attribute fails with `UnsupportedOperationException: Unsupported operator IN`.

I have a fix ready that handles both shapes Querydsl produces for `Ops.IN`:

- `collectionPath.contains(value)` → `(attribute=value)` (LDAP equality on a multi-valued attribute matches any value)
- `path.in(a, b)` → `(|(attribute=a)(attribute=b))`

Will submit a pull request shortly.
